import { useDataStore } from './useDataStore'

export interface BookmarkRecord {
  uuid: string
  bookId: number | null
  bookIdentity: string
  bookTitle: string
  bookAuthor: string
  coverPath: string | null
  chapterOrderIndex: number
  chapterTitle: string
  chapterOffset: number
  progressPercent: number
  summary: string
  createdAt: number
  updatedAt: number
}

export interface BookmarkTarget {
  uuid?: string
  chapterOrderIndex: number
  chapterOffset: number
}

export interface CreateBookmarkPayload {
  bookId: number
  bookIdentity: string
  bookTitle: string
  bookAuthor: string
  chapterOrderIndex: number
  chapterTitle: string
  chapterOffset: number
  progressPercent: number
  summary: string
}

function toBookmarkRecord(bm: any, coverFile: string | null): BookmarkRecord {
  return {
    uuid: String(bm.uuid || ''),
    bookId: bm.bookId === null || bm.bookId === undefined ? null : Number(bm.bookId),
    bookIdentity: String(bm.bookIdentity || ''),
    bookTitle: String(bm.bookTitle || ''),
    bookAuthor: String(bm.bookAuthor || ''),
    coverPath: coverFile ? `file:///${coverFile}` : null,
    chapterOrderIndex: Number(bm.chapterOrderIndex || 0),
    chapterTitle: String(bm.chapterTitle || ''),
    chapterOffset: Number(bm.chapterOffset || 0),
    progressPercent: Number(bm.progressPercent || 0),
    summary: String(bm.summary || ''),
    createdAt: Number(bm.createdAt || 0),
    updatedAt: Number(bm.updatedAt || 0),
  }
}

export async function fetchBookmarks(bookId?: number | null): Promise<BookmarkRecord[]> {
  const dataStore = useDataStore()
  const bookmarks = dataStore.getBookmarksWithCover(bookId ?? undefined)
  return bookmarks.map(bm => toBookmarkRecord(bm, bm.coverFile))
}

export async function createBookmark(payload: CreateBookmarkPayload): Promise<BookmarkRecord> {
  const dataStore = useDataStore()
  const now = Date.now()
  const uuid = crypto.randomUUID()

  const newBookmark = {
    id: 0, // will be auto-generated by addBookmark
    uuid,
    bookId: payload.bookId,
    bookIdentity: payload.bookIdentity,
    bookTitle: payload.bookTitle,
    bookAuthor: payload.bookAuthor,
    chapterOrderIndex: payload.chapterOrderIndex,
    chapterTitle: payload.chapterTitle,
    chapterOffset: Math.max(0, Math.floor(payload.chapterOffset)),
    progressPercent: Math.max(0, Math.min(100, Math.round(payload.progressPercent))),
    summary: payload.summary,
    createdAt: now,
    updatedAt: now,
  }

  // Generate ID
  const maxId = dataStore.bookmarks.value.reduce((max, b) => Math.max(max, b.id), 0)
  newBookmark.id = maxId + 1

  await dataStore.addBookmark(newBookmark)

  return {
    uuid,
    bookId: payload.bookId,
    bookIdentity: payload.bookIdentity,
    bookTitle: payload.bookTitle,
    bookAuthor: payload.bookAuthor,
    coverPath: null,
    chapterOrderIndex: payload.chapterOrderIndex,
    chapterTitle: payload.chapterTitle,
    chapterOffset: Math.max(0, Math.floor(payload.chapterOffset)),
    progressPercent: Math.max(0, Math.min(100, Math.round(payload.progressPercent))),
    summary: payload.summary,
    createdAt: now,
    updatedAt: now,
  }
}

export async function deleteBookmark(uuid: string): Promise<void> {
  const { deleteBookmark: del } = useDataStore()
  await del(uuid)
}

export async function deleteBookmarksForBook(bookId: number): Promise<void> {
  const { deleteBookmarksForBook: delForBook } = useDataStore()
  await delForBook(bookId)
}
