import { useDataStore } from './useDataStore'

export interface BookmarkRecord {
  uuid: string
  bookId: number | null
  bookIdentity: string
  bookTitle: string
  bookAuthor: string
  coverPath: string | null
  chapterOrderIndex: number
  chapterTitle: string
  chapterOffset: number
  progressPercent: number
  summary: string
  createdAt: number
  updatedAt: number
}

export interface BookmarkTarget {
  uuid?: string
  chapterOrderIndex: number
  chapterOffset: number
}

export interface CreateBookmarkPayload {
  bookId: number
  bookIdentity: string
  bookTitle: string
  bookAuthor: string
  chapterOrderIndex: number
  chapterTitle: string
  chapterOffset: number
  progressPercent: number
  summary: string
}

function toBookmarkRecord(bm: any, coverFile: string | null): BookmarkRecord {
  return {
    uuid: String(bm.uuid || ''),
    bookId: bm.bookId === null || bm.bookId === undefined ? null : Number(bm.bookId),
    bookIdentity: String(bm.bookIdentity || ''),
    bookTitle: String(bm.bookTitle || ''),
    bookAuthor: String(bm.bookAuthor || ''),
    coverPath: coverFile || null,
    chapterOrderIndex: Number(bm.chapterOrderIndex || 0),
    chapterTitle: String(bm.chapterTitle || ''),
    chapterOffset: Number(bm.chapterOffset || 0),
    progressPercent: Number(bm.progressPercent || 0),
    summary: String(bm.summary || ''),
    createdAt: Number(bm.createdAt || 0),
    updatedAt: Number(bm.updatedAt || 0),
  }
}

export async function fetchBookmarks(bookId?: number | null): Promise<BookmarkRecord[]> {
  const [bookmarks, books] = await Promise.all([
    readBookmarkRows(),
    window.electronAPI.library.getBookshelfBooks(),
  ])
  const coverByBookId = new Map(books.map(book => [book.id, book.coverFile]))
  return bookmarks
    .filter(bookmark => bookId === undefined || bookId === null || Number(bookmark.bookId) === bookId)
    .sort((a, b) => Number(b.updatedAt || 0) - Number(a.updatedAt || 0))
    .map(bookmark => {
      const localBookId = bookmark.bookId === null || bookmark.bookId === undefined ? null : Number(bookmark.bookId)
      return toBookmarkRecord(bookmark, localBookId ? (coverByBookId.get(localBookId) ?? null) : null)
    })
}

export async function createBookmark(payload: CreateBookmarkPayload): Promise<BookmarkRecord> {
  const now = Date.now()
  const uuid = crypto.randomUUID()
  const bookmarks = await readBookmarkRows()

  const newBookmark = {
    id: 0, // will be auto-generated by addBookmark
    uuid,
    bookId: payload.bookId,
    bookIdentity: payload.bookIdentity,
    bookTitle: payload.bookTitle,
    bookAuthor: payload.bookAuthor,
    chapterOrderIndex: payload.chapterOrderIndex,
    chapterTitle: payload.chapterTitle,
    chapterOffset: Math.max(0, Math.floor(payload.chapterOffset)),
    progressPercent: Math.max(0, Math.min(100, Math.round(payload.progressPercent))),
    summary: payload.summary,
    createdAt: now,
    updatedAt: now,
  }

  // Generate ID
  const maxId = bookmarks.reduce((max, b) => Math.max(max, Number(b.id || 0)), 0)
  newBookmark.id = maxId + 1

  bookmarks.push(newBookmark)
  await writeBookmarkRows(bookmarks)

  return {
    uuid,
    bookId: payload.bookId,
    bookIdentity: payload.bookIdentity,
    bookTitle: payload.bookTitle,
    bookAuthor: payload.bookAuthor,
    coverPath: null,
    chapterOrderIndex: payload.chapterOrderIndex,
    chapterTitle: payload.chapterTitle,
    chapterOffset: Math.max(0, Math.floor(payload.chapterOffset)),
    progressPercent: Math.max(0, Math.min(100, Math.round(payload.progressPercent))),
    summary: payload.summary,
    createdAt: now,
    updatedAt: now,
  }
}

export async function deleteBookmark(uuid: string): Promise<void> {
  const bookmarks = await readBookmarkRows()
  await writeBookmarkRows(bookmarks.filter(bookmark => bookmark.uuid !== uuid))
}

export async function deleteBookmarksForBook(bookId: number): Promise<void> {
  const bookmarks = await readBookmarkRows()
  await writeBookmarkRows(bookmarks.filter(bookmark => Number(bookmark.bookId) !== bookId))
}

async function readBookmarkRows(): Promise<any[]> {
  const rows = await window.electronAPI.data.readEntity('bookmarks')
  return Array.isArray(rows) ? rows : []
}

async function writeBookmarkRows(bookmarks: any[]): Promise<void> {
  const store = useDataStore()
  if (store.dataLoaded.value) {
    store.bookmarks.value = bookmarks as any
  }
  await window.electronAPI.data.writeEntity('bookmarks', bookmarks)
}
